window.$ = require('jquery');
require('../brat/client/lib/jquery.svg.min.js');
require('../brat/client/lib/jquery.svgdom.min.js');
require('../brat/client/src/configuration.js');
require('../brat/client/src/util.js');
require('../brat/client/src/annotation_log.js');
require('../brat/client/lib/webfont.js');
require('../brat/client/src/dispatcher.js');
require('../brat/client/src/url_monitor.js');
require('../brat/client/src/visualizer.js');
require('./report.js');
